//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;

namespace Esha.Genesis.Services.Client
{
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class FoodsSearchRequest1
    {

        [MessageBodyMember(Namespace = "http://ns.esha.com/2013/genesisapi")]
        public FoodsSearchRequest FoodsSearchRequest;

        public FoodsSearchRequest1()
        {
        }

        public FoodsSearchRequest1(FoodsSearchRequest FoodsSearchRequest)
        {
            this.FoodsSearchRequest = FoodsSearchRequest;
        }
    }
}
